source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'iGitHub' do
    pod 'Alamofire', '~> 4.0'
    pod 'UIColor_Hex_Swift', '~> 3.0.1'
    pod 'SnapKit', '~> 3.0.1'
    pod 'Kingfisher', '~> 3.1.0'
    pod 'YYKit', '~> 1.0.9'
    pod 'XCGLogger', '~> 4.0.0'
end
